### PR TITLE
Uses getter instead of `lookup`

### LINKED ISSUE #32: Uncaught TypeError: instance.lookup is not a function
https://github.com/twokul/ember-cli-bugsnag/blob/master/app/instance-initializers/bugsnag.js#L32

### PR DESCRIPTION
**Pull request by twokul**
Fixes #32

### CODE REVIEW

**Comment by bdvholmes** [comment]
Looks good, I'm not a travis expert but is this a dependency issue?

**Comment by mmun** [comment]
I suspect the initializer is crashing the tests before they connect to testem, causing the timeout to occur. In other words, the bug doesn't seem fixed yet.

**Comment by twokul** [comment]
@mmun @bdvholmes took another look. can't see any initializer crashes, gonna try to add a simple integration test to see if I can surface the issue

**Comment by mmun** [comment]
@twokul I'll take a look soon! Thanks for raising the issue.

**Pull request merged**
