### PR TITLE
Enable endpoint config

### PR DESCRIPTION
**Pull request by kcin1018**
I am working on a project with a self hosted Bugsnag instance.  I needed to update the script to add the endpoint configuration so that it would work with both the default hosting as well as a specified hosting.

### CODE REVIEW

**Comment by kcin1018** [comment]
Not sure about the tests, seemed to just stall.

**Comment by kcin1018** [comment]
Fixed the Travis CI integration and updated to ember-cli 2.5.0

**Comment by binhums** [comment]
Wow that's great. Is the ember-cli 2.5.0 upgrade required to get the tests passing?

**Comment by binhums** [comment]
@kcin1018 If not it is probably worth splitting these out into two separate PRs

**Comment by kcin1018** [comment]
@binhums I don't think that ember-cli 2.5.0 is required.  I am not sure how to split the PRs so any help with that would be great.  Or I can try to create new PRs with each part.

**Comment by binhums** [comment]
Interesting that that resolved our travis problems. I'm reluctant to do an ember version upgrade without testing separately. @kcin1018 happy to work together with you on splitting these out. Would you be interested in finding a time to pair together on this?

**Comment by binhums** [comment]
Relates to #39

**Comment by kcin1018** [comment]
@binhums Sure, never done it.  I am new to contributing to anything but I am willing to help.

**Comment by binhums** [comment]
@kcin1018 and I worked together to split these out into #42, #43 and #44.

Thanks so much Kevin - closing this PR.

**Pull request closed without merging**
